<a href="https://colab.research.google.com/github/gowtham555/gowtham/blob/main/ipl_match_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv('IPL2020_Match_data.csv')
print(df)

    Match_id  Match_date  Match_day                        Match_stadium  \
0        1.0  19-09-2020   Saturday                 SHEIKH ZAYED STADIUM
1        2.0  20-09-2020     Sunday  DUBAI INTERNATIONAL CRICKET STADIUM
2        3.0  21-09-2020     Monday  DUBAI INTERNATIONAL CRICKET STADIUM
3        4.0  22-09-2020    Tuesday             SHARJAH CRICKET STADIUM,
4        5.0  23-09-2020  Wednesday                 SHEIKH ZAYED STADIUM
5        6.0  24-09-2020   Thursday  DUBAI INTERNATIONAL CRICKET STADIUM
6        7.0  25-09-2020     Friday  DUBAI INTERNATIONAL CRICKET STADIUM
7        NaN         NaN        NaN                                  NaN
8        NaN         NaN        NaN                                  NaN
9        NaN         NaN        NaN                                  NaN
10       NaN         NaN        NaN                                  NaN
11       NaN         NaN        NaN                                  NaN
12       NaN         NaN        NaN                                  NaN
13       NaN         NaN        NaN                                  NaN
14       NaN         NaN        NaN                                  NaN
15       NaN         NaN        NaN                                  NaN

   Location_id Match_location  Season                        Team1  \
0          Abu      ABU DHABI  2020.0               Mumbai Indians
1           Du          DUBAI  2020.0               Delhi Capitals
2           Du          DUBAI  2020.0  Royal Challengers Bangalore
3          sha        SHARJAH  2020.0             Rajasthan Royals
4          Abu      ABU DHABI  2020.0               Mumbai Indians
5           Du          DUBAI  2020.0              Kings XI Punjab
6           Du          DUBAI  2020.0               Delhi Capitals
7          NaN            NaN     NaN                          NaN
8          NaN            NaN     NaN                          NaN
9          NaN            NaN     NaN                          NaN
10         NaN            NaN     NaN                          NaN
11         NaN            NaN     NaN                          NaN
12         NaN            NaN     NaN                          NaN
13         NaN            NaN     NaN                          NaN
14         NaN            NaN     NaN                          NaN
15         NaN            NaN     NaN                          NaN

                          Team2                     Toss_won  ... Team1_sixes  \
0           Chennai Super Kings          Chennai Super Kings  ...         4.0
1               Kings XI Punjab              Kings XI Punjab  ...         6.0
2           Sunrisers Hyderabad          Sunrisers Hyderabad  ...         4.0
3           Chennai Super Kings          Chennai Super Kings  ...        17.0
4         Kolkata Knight Riders        Kolkata Knight Riders  ...         9.0
5   Royal Challengers Bangalore  Royal Challengers Bangalore  ...         7.0
6           Chennai Super Kings          Chennai Super Kings  ...         2.0
7                           NaN                          NaN  ...         NaN
8                           NaN                          NaN  ...         NaN
9                           NaN                          NaN  ...         NaN
10                          NaN                          NaN  ...         NaN
11                          NaN                          NaN  ...         NaN
12                          NaN                          NaN  ...         NaN
13                          NaN                          NaN  ...         NaN
14                          NaN                          NaN  ...         NaN
15                           ,.                          NaN  ...         NaN

   Team2_sixes Total_fours  Team1_fours  Team2_fours  Total_extras_given  \
0          5.0        31.0         15.0         16.0                 9.0
1          6.0        25.0         13.0         12.0                17.0
2          3.0        27.0         13.0         14.0                20.0
3         16.0        18.0          9.0          9.0                14.0
4          7.0        26.0         13.0         13.0                19.0
5          3.0        31.0         21.0         10.0                20.0
6         12.0        20.0         19.0          1.0                13.0
7          NaN         NaN          NaN          NaN                 NaN
8          NaN         NaN          NaN          NaN                 NaN
9          NaN         NaN          NaN          NaN                 NaN
10         NaN         NaN          NaN          NaN                 NaN
11         NaN         NaN          NaN          NaN                 NaN
12         NaN         NaN          NaN          NaN                 NaN
13         NaN         NaN          NaN          NaN                 NaN
14         NaN         NaN          NaN          NaN                 NaN
15         NaN         NaN          NaN          NaN                 NaN

    Team1_extras_runs Team2_extras_runs  \
0                 5.0               4.0
1                 9.0               8.0
2                 5.0              15.0
3                 9.0               5.0
4                 5.0              14.0
5                11.0               9.0
6                 8.0               5.0
7                 NaN               NaN
8                 NaN               NaN
9                 NaN               NaN
10                NaN               NaN
11                NaN               NaN
12                NaN               NaN
13                NaN               NaN
14                NaN               NaN
15                NaN               NaN

                                              Umpires  \
0   Virender Sharma (IND), Chris Gaffaney (NZ) and...
1   Nitin Menon (IND), Anil Chaudhary (IND) and Pa...
2   Nitin Menon (IND), Anil Dandekar (IND) and Ani...
3   Chettithody Shamshuddin (IND), Vineet Kulkarni...
4   Chris Gaffaney (NZ), Sundaram Ravi (IND) and V...
5   Paul Reiffel (AUS), Anil Chaudhary (IND) and N...
6   Richard Illingworth (ENG), KN Ananthapadmanabh...
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN

                    Match refereee
0                Manu Nayyar (IND)
1            Javagal Srinath (IND)
2              Prakash Bhatt (IND)
3   Vengalil Narayanan Kutty (IND)
4                Manu Nayyar (IND)
5            Javagal Srinath (IND)
6   Vengalil Narayanan Kutty (IND)
7                              NaN
8                              NaN
9                              NaN
10                             NaN
11                             NaN
12                             NaN
13                             NaN
14                             NaN
15                             NaN

[16 rows x 36 columns]

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv('IPL2020_Match_data.csv')
print(df)
df.isnull().sum()

    Match_id  Match_date  Match_day                        Match_stadium  \
0        1.0  19-09-2020   Saturday                 SHEIKH ZAYED STADIUM
1        2.0  20-09-2020     Sunday  DUBAI INTERNATIONAL CRICKET STADIUM
2        3.0  21-09-2020     Monday  DUBAI INTERNATIONAL CRICKET STADIUM
3        4.0  22-09-2020    Tuesday             SHARJAH CRICKET STADIUM,
4        5.0  23-09-2020  Wednesday                 SHEIKH ZAYED STADIUM
5        6.0  24-09-2020   Thursday  DUBAI INTERNATIONAL CRICKET STADIUM
6        7.0  25-09-2020     Friday  DUBAI INTERNATIONAL CRICKET STADIUM
7        NaN         NaN        NaN                                  NaN
8        NaN         NaN        NaN                                  NaN
9        NaN         NaN        NaN                                  NaN
10       NaN         NaN        NaN                                  NaN
11       NaN         NaN        NaN                                  NaN
12       NaN         NaN        NaN                                  NaN
13       NaN         NaN        NaN                                  NaN
14       NaN         NaN        NaN                                  NaN
15       NaN         NaN        NaN                                  NaN

   Location_id Match_location  Season                        Team1  \
0          Abu      ABU DHABI  2020.0               Mumbai Indians
1           Du          DUBAI  2020.0               Delhi Capitals
2           Du          DUBAI  2020.0  Royal Challengers Bangalore
3          sha        SHARJAH  2020.0             Rajasthan Royals
4          Abu      ABU DHABI  2020.0               Mumbai Indians
5           Du          DUBAI  2020.0              Kings XI Punjab
6           Du          DUBAI  2020.0               Delhi Capitals
7          NaN            NaN     NaN                          NaN
8          NaN            NaN     NaN                          NaN
9          NaN            NaN     NaN                          NaN
10         NaN            NaN     NaN                          NaN
11         NaN            NaN     NaN                          NaN
12         NaN            NaN     NaN                          NaN
13         NaN            NaN     NaN                          NaN
14         NaN            NaN     NaN                          NaN
15         NaN            NaN     NaN                          NaN

                          Team2                     Toss_won  ... Team1_sixes  \
0           Chennai Super Kings          Chennai Super Kings  ...         4.0
1               Kings XI Punjab              Kings XI Punjab  ...         6.0
2           Sunrisers Hyderabad          Sunrisers Hyderabad  ...         4.0
3           Chennai Super Kings          Chennai Super Kings  ...        17.0
4         Kolkata Knight Riders        Kolkata Knight Riders  ...         9.0
5   Royal Challengers Bangalore  Royal Challengers Bangalore  ...         7.0
6           Chennai Super Kings          Chennai Super Kings  ...         2.0
7                           NaN                          NaN  ...         NaN
8                           NaN                          NaN  ...         NaN
9                           NaN                          NaN  ...         NaN
10                          NaN                          NaN  ...         NaN
11                          NaN                          NaN  ...         NaN
12                          NaN                          NaN  ...         NaN
13                          NaN                          NaN  ...         NaN
14                          NaN                          NaN  ...         NaN
15                           ,.                          NaN  ...         NaN

   Team2_sixes Total_fours  Team1_fours  Team2_fours  Total_extras_given  \
0          5.0        31.0         15.0         16.0                 9.0
1          6.0        25.0         13.0         12.0                17.0
2          3.0        27.0         13.0         14.0                20.0
3         16.0        18.0          9.0          9.0                14.0
4          7.0        26.0         13.0         13.0                19.0
5          3.0        31.0         21.0         10.0                20.0
6         12.0        20.0         19.0          1.0                13.0
7          NaN         NaN          NaN          NaN                 NaN
8          NaN         NaN          NaN          NaN                 NaN
9          NaN         NaN          NaN          NaN                 NaN
10         NaN         NaN          NaN          NaN                 NaN
11         NaN         NaN          NaN          NaN                 NaN
12         NaN         NaN          NaN          NaN                 NaN
13         NaN         NaN          NaN          NaN                 NaN
14         NaN         NaN          NaN          NaN                 NaN
15         NaN         NaN          NaN          NaN                 NaN

    Team1_extras_runs Team2_extras_runs  \
0                 5.0               4.0
1                 9.0               8.0
2                 5.0              15.0
3                 9.0               5.0
4                 5.0              14.0
5                11.0               9.0
6                 8.0               5.0
7                 NaN               NaN
8                 NaN               NaN
9                 NaN               NaN
10                NaN               NaN
11                NaN               NaN
12                NaN               NaN
13                NaN               NaN
14                NaN               NaN
15                NaN               NaN

                                              Umpires  \
0   Virender Sharma (IND), Chris Gaffaney (NZ) and...
1   Nitin Menon (IND), Anil Chaudhary (IND) and Pa...
2   Nitin Menon (IND), Anil Dandekar (IND) and Ani...
3   Chettithody Shamshuddin (IND), Vineet Kulkarni...
4   Chris Gaffaney (NZ), Sundaram Ravi (IND) and V...
5   Paul Reiffel (AUS), Anil Chaudhary (IND) and N...
6   Richard Illingworth (ENG), KN Ananthapadmanabh...
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN

                    Match refereee
0                Manu Nayyar (IND)
1            Javagal Srinath (IND)
2              Prakash Bhatt (IND)
3   Vengalil Narayanan Kutty (IND)
4                Manu Nayyar (IND)
5            Javagal Srinath (IND)
6   Vengalil Narayanan Kutty (IND)
7                              NaN
8                              NaN
9                              NaN
10                             NaN
11                             NaN
12                             NaN
13                             NaN
14                             NaN
15                             NaN

[16 rows x 36 columns]

Match_id                    9
Match_date                  9
Match_day                   9
Match_stadium               9
Location_id                 9
Match_location              9
Season                      9
Team1                       9
Team2                       8
Toss_won                    9
Toss_decision               9
Result                      9
Winner                      9
Team1_score                 9
Team2_score                 9
Team1_wickets               9
Team2_wickets               9
Win_by_super_over_run       9
Win_by_super_over_wicket    9
Win_by_runs                 9
Win_by_wickets              9
Player_of_the_match         9
Total overs                 9
Team1_bat_overs             9
Team2_bat_overs             9
Total_sixes                 9
Team1_sixes                 9
Team2_sixes                 9
Total_fours                 9
Team1_fours                 9
Team2_fours                 9
Total_extras_given          9
Team1_extras_runs           9
Team2_extras_runs           9
Umpires                     9
Match refereee              9
dtype: int64

In [ ]:
import numpy as np
df = pd.read_csv('IPL2020_Match_data.csv')
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)
print(np.add(a,b))
print(a.shape)
print(b.shape)

[[9 9 2]
 [0 9 6]
 [5 1 9]]
[[11 16 10]
 [13 10 16]
 [16 16 14]]
[[20 25 12]
 [13 19 22]
 [21 17 23]]
(3, 3)
(3, 3)

In [ ]:
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv('IPL2020_Match_data.csv')
df.head()

,Match_id,Match_date,Match_day,Match_stadium,Location_id,Match_location,Season,Team1,Team2,Toss_won,...,Team1_sixes,Team2_sixes,Total_fours,Team1_fours,Team2_fours,Total_extras_given,Team1_extras_runs,Team2_extras_runs,Umpires,Match refereee
0,1.0,19-09-2020,Saturday,SHEIKH ZAYED STADIUM,Abu,ABU DHABI,2020.0,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,...,4.0,5.0,31.0,15.0,16.0,9.0,5.0,4.0,"Virender Sharma (IND), Chris Gaffaney (NZ) and...",Manu Nayyar (IND)
1,2.0,20-09-2020,Sunday,DUBAI INTERNATIONAL CRICKET STADIUM,Du,DUBAI,2020.0,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,...,6.0,6.0,25.0,13.0,12.0,17.0,9.0,8.0,"Nitin Menon (IND), Anil Chaudhary (IND) and Pa...",Javagal Srinath (IND)
2,3.0,21-09-2020,Monday,DUBAI INTERNATIONAL CRICKET STADIUM,Du,DUBAI,2020.0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,...,4.0,3.0,27.0,13.0,14.0,20.0,5.0,15.0,"Nitin Menon (IND), Anil Dandekar (IND) and Ani...",Prakash Bhatt (IND)
3,4.0,22-09-2020,Tuesday,"SHARJAH CRICKET STADIUM,",sha,SHARJAH,2020.0,Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,...,17.0,16.0,18.0,9.0,9.0,14.0,9.0,5.0,"Chettithody Shamshuddin (IND), Vineet Kulkarni...",Vengalil Narayanan Kutty (IND)
4,5.0,23-09-2020,Wednesday,SHEIKH ZAYED STADIUM,Abu,ABU DHABI,2020.0,Mumbai Indians,Kolkata Knight Riders,Kolkata Knight Riders,...,9.0,7.0,26.0,13.0,13.0,19.0,5.0,14.0,"Chris Gaffaney (NZ), Sundaram Ravi (IND) and V...",Manu Nayyar (IND)

# New section